language: minimal
dist: xenial

services:
  - docker

env:
  - STACK_VERSION=1.9.3

cache:
  directories:
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/.stack-work
    - docker

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - |
    travis_retry \
    curl -L https://github.com/commercialhaskell/stack/releases/download/v$STACK_VERSION/stack-$STACK_VERSION-linux-x86_64.tar.gz | \
    tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - docker save earnestresearch/aws-lambda-haskell-platform:lts-12.24 | gzip > docker/aws-lambda-haskell-platform.tar.gz

before_script:
  - gzip -dc docker/aws-lambda-haskell-platform.tar.gz | docker load
  - stack docker pull

script:
  - make build
