language: minimal
dist: xenial

services:
  - docker

env:
  - STACK_VERSION=1.9.3

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - |
    travis_retry \
    curl -L https://github.com/commercialhaskell/stack/releases/download/v$STACK_VERSION/stack-$STACK_VERSION-linux-x86_64.tar.gz | \
    tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack docker pull

script:
  - make build
