name:                aws-lambda-haskell-runtime-client
version:             0.1.0.0
github:              "EarnestResearch/aws-lambda-haskell-runtime-client"
license:             MIT
author:              "Louis Vera"
maintainer:          "dcq-team@earnestresearch.com"
copyright:           "Earnest Research 2019"
category:            AWS
synopsis:            AWS Lambda Haskell Runtime Client

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/EarnestResearch/aws-lambda-haskell-runtime-client#readme>

dependencies:
- aeson                             >= 1.4.2 && < 1.5
- base                              >= 4.7 && < 5
- bytestring                        >= 0.10.8 && < 0.11
- text                              >= 1.2.3 && < 1.3
- transformers                      >= 0.5.6 && < 0.6
- unordered-containers              >= 0.2.10 && < 0.3
- http-client                       >= 0.5.14 && < 0.7
- mtl                               >= 2.2.2 && < 2.3
- http-types                        >= 0.12.3 && < 0.13
- lens                              >= 4.17.1 && < 4.18
- monad-logger                      >= 0.3.30 && < 0.4
- wreq                              >= 0.5.3 && < 0.6                  

library:
  source-dirs: src

flags:
  static:
    description: Static build
    manual: true
    default: false

executables:
  api-gateway-exe:
    main:                Main.hs
    source-dirs:         examples/api-gateway
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
    - condition: flag(static)
      ld-options:
      - -static
      - -pthread
      cc-options: -static
    dependencies:
    - aws-lambda-haskell-runtime-client
  kinesis-exe:
    main:                Main.hs
    source-dirs:         examples/kinesis
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
    - condition: flag(static)
      ld-options:
      - -static
      - -pthread
      cc-options: -static
    dependencies:
    - aws-lambda-haskell-runtime-client
  s3-exe:
    main:                Main.hs
    source-dirs:         examples/s3
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
    - condition: flag(static)
      ld-options:
      - -static
      - -pthread
      cc-options: -static
    dependencies:
    - aws-lambda-haskell-runtime-client
  sns-exe:
    main:                Main.hs
    source-dirs:         examples/sns
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
    - condition: flag(static)
      ld-options:
      - -static
      - -pthread
      cc-options: -static
    dependencies:
    - aws-lambda-haskell-runtime-client

tests:
  aws-lambda-haskell-runtime-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aws-lambda-haskell-runtime-client
    - HUnit                 >= 1.6.0.0 && < 1.7
    - hspec                 >= 2.6.1 && < 2.8
    - keys                  >= 3.12.2 && < 3.13
