name:                aws-lambda-haskell-runtime
version:             0.1.0.0
github:              "EarnestResearch/aws-lambda-haskell-runtime"
license:             Apache-2.0
author:              "Louis Vera"
maintainer:          "lvera@earnestresearch.com"
copyright:           "Earnest Research 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/EarnestResearch/aws-lambda-haskell-runtime#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- lens
- monad-logger
- mtl
- text
- transformers
- unordered-containers
- wreq

library:
  source-dirs: src

executables:
  aws-lambda-haskell-runtime-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aws-lambda-haskell-runtime

tests:
  aws-lambda-haskell-runtime-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aws-lambda-haskell-runtime
