name:                aws-lambda-haskell-runtime-client
version:             0.1.0.0
github:              "EarnestResearch/aws-lambda-haskell-runtime-client"
license:             MIT
author:              "Louis Vera"
maintainer:          "lvera@earnestresearch.com"
copyright:           "Earnest Research 2019"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/EarnestResearch/aws-lambda-haskell-runtime-client#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- http-client
- lens
- monad-logger
- mtl
- text
- transformers
- unordered-containers
- wreq

library:
  source-dirs: src

executables:
  api-gateway-exe:
    main:                Main.hs
    source-dirs:         examples/api-gateway
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aws-lambda-haskell-runtime-client
  kinesis-exe:
    main:                Main.hs
    source-dirs:         examples/kinesis
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aws-lambda-haskell-runtime-client
  s3-exe:
    main:                Main.hs
    source-dirs:         examples/s3
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aws-lambda-haskell-runtime-client

tests:
  aws-lambda-haskell-runtime-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aws-lambda-haskell-runtime-client
