name:                aws-lambda-haskell-runtime-client
version:             0.1.0.0
github:              "EarnestResearch/aws-lambda-haskell-runtime-client"
license:             Apache-2.0
author:              "Louis Vera"
maintainer:          "lvera@earnestresearch.com"
copyright:           "Earnest Research 2019"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/EarnestResearch/aws-lambda-haskell-runtime-client#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- lens
- monad-logger
- mtl
- text
- transformers
- unordered-containers
- wreq

library:
  source-dirs: src

executables:
  aws-lambda-haskell-runtime-client-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aws-lambda-haskell-runtime-client

tests:
  aws-lambda-haskell-runtime-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aws-lambda-haskell-runtime-client
