name: yambda
version: '0.1.0.1'
synopsis: AWS Lambda Haskell Runtime Client
description: Please see the README on GitHub at <https://github.com/EarnestResearch/yambda#readme>
category: AWS
author: Louis Vera
maintainer: dcq-team@earnestresearch.com
copyright: Earnest Research 2019
license: MIT
github: EarnestResearch/yambda

extra-source-files:
- README.md
- ChangeLog.md

ghc-options:
- -Wall

dependencies:
- aeson >=1.4.2 && <1.5
- base >=4.7 && <5
- bytestring >=0.10.8 && <0.11
- containers >0.6.2
- http-types >=0.12.3 && <0.13
- lens >=4.17.1 && <4.19
- monad-logger >=0.3.30 && <0.4
- mtl >=2.2.2 && <2.3
- text >=1.2.3 && <1.3
- unliftio >0.2.12
- unordered-containers >=0.2.10 && <0.3

library:
  source-dirs: src
  generated-other-modules:
    - Paths_yambda
  dependencies:
  - base64 >0.4
  - dhall >=1.26.1 && <1.31
  - http-client >=0.5.14 && <0.7
  - wreq >=0.5.3 && <0.6

tests:
  yambda-test:
    main: Spec.hs
    source-dirs: test
    generated-other-modules:
      - Paths_yambda
    ghc-options:
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - HUnit >=1.6.0.0 && <1.7
    - yambda
    - hspec >=2.6.1 && <2.8
    - keys >=3.12.2 && <3.13

flags:
  static:
    description: Static build
    manual: true
    default: false

data-dir:
  "data"

data-files:
- ! '*.json'
