name: aws-lambda-haskell-runtime-client-wai
version: '0.1.0.0'
synopsis: AWS Lambda Haskell Runtime Client' WAI bindings
description: Please see the README on GitHub at <https://github.com/EarnestResearch/aws-lambda-haskell-runtime-client#readme>
category: AWS
author: Earnest research team
maintainer: dcq-team@earnestresearch.com
copyright: Earnest Research 2019
license: MIT
github: EarnestResearch/aws-lambda-haskell-runtime-client

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- aeson >=1.4.2 && <1.5
- aws-lambda-haskell-runtime-client
- base >=4.7 && <5
- base64 >0.4
- bytestring >=0.10.8 && <0.11
- http-types >0.12
- lens >=4.17.1 && <4.19
- monad-logger >=0.3.30 && <0.4
- mtl >=2.2.2 && <2.3
- text >=1.2.3 && <1.3
- unliftio >0.2.12
- unordered-containers >=0.2.10 && <0.3
- wai >=3.2 && <4.0

library:
  source-dirs: src

flags:
  static:
    description: Static build
    manual: true
    default: false
