name: aws-lambda-haskell-runtime-client-wai
version: '0.1.0.0'
synopsis: AWS Lambda Haskell Runtime Client' WAI bindings
description: Please see the README on GitHub at <https://github.com/EarnestResearch/aws-lambda-haskell-runtime-client#readme>
category: AWS
author: Earnest research team
maintainer: dcq-team@earnestresearch.com
copyright: Earnest Research 2019
license: MIT
github: EarnestResearch/aws-lambda-haskell-runtime-client

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- aeson >=1.4.2 && <1.5
- aws-lambda-haskell-runtime-client
- base >=4.7 && <5
- base64 >0.4
- bytestring >=0.10.8 && <0.11
- case-insensitive >1.2
- containers >0.6.2
- http-types >0.12
- lens >=4.17.1 && <4.19
- monad-logger >=0.3.30 && <0.4
- mtl >=2.2.2 && <2.3
- network >3.1
- text >=1.2.3 && <1.3
- unliftio >0.2.12
- unordered-containers >=0.2.10 && <0.3
- wai >=3.2 && <4.0

library:
  source-dirs: src
  generated-other-modules:
    - Paths_aws_lambda_haskell_runtime_client_wai

tests:
  aws-lambda-haskell-runtime-client-wai-test:
    main: Spec.hs
    source-dirs: test
    generated-other-modules:
      - Paths_aws_lambda_haskell_runtime_client_wai
    dependencies:
      - HUnit >=1.6.0.0 && <1.7
      - aws-lambda-haskell-runtime-client-wai
      - hspec >=2.6.1 && <2.8
    ghc-options:
      - -threaded
      - -with-rtsopts=-N

flags:
  static:
    description: Static build
    manual: true
    default: false

data-dir:
  "data"

data-files:
  - ! '*.json'
